### ISSUE TITLE
how to train a new LDG

### ISSUE THREAD

**Issue by hhhhnwl** [zengqunzhao/EfficientFace#10]
I  need change expression labels, how to train LDG in new dataset

**Comment by zengqunzhao** [comment]
> I need change expression labels, how to train LDG in new dataset

Firstly, the LDG needs to be pre-trained on MS-Celeb-1M. Then, the LDG needs to be trained on corresponding FER datasets. After finishing these two steps, you can train the EfficientFace on corresponding FER datasets. 
The pre-trained LDG on MS-Celeb-1M can be found in README->Pre-trained Models part.

Best,
Zeke
