### ISSUE TITLE
EfficientFace trained FER models?

### ISSUE THREAD

**Issue by katerynaCh** [zengqunzhao/EfficientFace#11]
Hi! I see that you recently shared several LDG models trained for FER. Do you have a plan to also share the trained EfficientFace models trained on any FER datasets as per paper?

Thanks!

**Comment by zengqunzhao** [comment]
> Hi! I see that you recently shared several LDG models trained for FER. Do you have a plan to also share the trained EfficientFace models trained on any FER datasets as per paper?
> 
> Thanks!

The trained EfficientFace models have been released, please check in the README.

Best,
Zeke
