### ISSUE TITLE
Face extraction and alignment of RAF dataset

### ISSUE THREAD

**Issue by Rassibassi** [zengqunzhao/EfficientFace#12]
Hi,

great work, and thanks for sharing. I'm trying to train my own version of the model and I have a quick question.

Did you use the aligned versions from the RAF-DB dataset or did you use a custom face detection and alignment method.

The RAF-DB has two folders `original` and `aligned`. From your README it seems that you used the files from the `original` folder, e.g. `test_0001.jpg`. In the `aligned` folder the naming is as follows `test_0001_aligned.jpg`.

Thanks,
Rasmus

**Comment by zengqunzhao** [comment]
> Hi,
> 
> great work, and thanks for sharing. I'm trying to train my own version of the model and I have a quick question.
> 
> Did you use the aligned versions from the RAF-DB dataset or did you use a custom face detection and alignment method.
> 
> The RAF-DB has two folders `original` and `aligned`. From your README it seems that you used the files from the `original` folder, e.g. `test_0001.jpg`. In the `aligned` folder the naming is as follows `test_0001_aligned.jpg`.
> 
> Thanks, Rasmus

Thanks for your interest.
Yes, we used the aligned versions from the RAF-DB dataset.
