### ISSUE TITLE
Smaller model size

### ISSUE THREAD

**Issue by Rassibassi** [zengqunzhao/EfficientFace#13]
Hi,

I'm looking into a real-time application where speed is more important than accuracy. So I am interested in your opinion. If you had to decrease the size of the model by 10x, 5x and 2x, where would you truncate the model.

E.g. by decreasing the stages and out channels, but by how much? [1]

[1]  `model = EfficientFace([4, 8, 4], [29, 116, 232, 464, 1024])`
https://github.com/zengqunzhao/EfficientFace/blob/350845c9fb0aae1cf14e728591ebb70b20ae7a22/models/EfficientFace.py#L198

Thanks,
Rasmus

**Comment by zengqunzhao** [comment]
> Hi,
> 
> I'm looking into a real-time application where speed is more important than accuracy. So I am interested in your opinion. If you had to decrease the size of the model by 10x, 5x and 2x, where would you truncate the model.
> 
> E.g. by decreasing the stages and out channels, but by how much? [1]
> 
> [1] `model = EfficientFace([4, 8, 4], [29, 116, 232, 464, 1024])`
> 
> https://github.com/zengqunzhao/EfficientFace/blob/350845c9fb0aae1cf14e728591ebb70b20ae7a22/models/EfficientFace.py#L198
> 
> Thanks, Rasmus

I think it depends on your lower limit of accuracy. In my view, you can decrease the input image size and channels. But more ablation studies should be conducted to investigate the effect.
