### ISSUE TITLE
Problem setting up the environment

### ISSUE THREAD

**Issue by leodollinger** [zengqunzhao/EfficientFace#14]
I'm trying to run the project on my pc, but i keep running into the following error:
```
Traceback (most recent call last):
  File "D:\LEO\2-Estudos\sem8\tcc2\git reconhecimento de expressoes\EfficientFace\main.py", line 383, in <module>
    main()
  File "D:\LEO\2-Estudos\sem8\tcc2\git reconhecimento de expressoes\EfficientFace\main.py", line 99, in main
    train_dataset = datasets.ImageFolder(traindir,
  File "C:\Users\leodo\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\datasets\folder.py", line 310, in __init__
    super(ImageFolder, self).__init__(root, loader, IMG_EXTENSIONS if is_valid_file is None else None,
  File "C:\Users\leodo\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\datasets\folder.py", line 145, in __init__
    classes, class_to_idx = self.find_classes(self.root)
  File "C:\Users\leodo\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\datasets\folder.py", line 221, in find_classes
    return find_classes(directory)
  File "C:\Users\leodo\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\datasets\folder.py", line 42, in find_classes
    raise FileNotFoundError(f"Couldn't find any class folder in {directory}.")
FileNotFoundError: Couldn't find any class folder in D:\LEO\2-Estudos\sem8\tcc2\git reconhecimento de expressoes\EfficientFace\train.
```
Can you help me?

**Comment by qitingtingvi** [comment]
The compressed package of pth cannot be decompressed as a tar file. What statements do you need to decompress open tar

**Comment by zengqunzhao** [comment]
> I'm trying to run the project on my pc, but i keep running into the following error:
> 
> ```
> Traceback (most recent call last):
>   File "D:\LEO\2-Estudos\sem8\tcc2\git reconhecimento de expressoes\EfficientFace\main.py", line 383, in <module>
>     main()
>   File "D:\LEO\2-Estudos\sem8\tcc2\git reconhecimento de expressoes\EfficientFace\main.py", line 99, in main
>     train_dataset = datasets.ImageFolder(traindir,
>   File "C:\Users\leodo\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\datasets\folder.py", line 310, in __init__
>     super(ImageFolder, self).__init__(root, loader, IMG_EXTENSIONS if is_valid_file is None else None,
>   File "C:\Users\leodo\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\datasets\folder.py", line 145, in __init__
>     classes, class_to_idx = self.find_classes(self.root)
>   File "C:\Users\leodo\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\datasets\folder.py", line 221, in find_classes
>     return find_classes(directory)
>   File "C:\Users\leodo\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\datasets\folder.py", line 42, in find_classes
>     raise FileNotFoundError(f"Couldn't find any class folder in {directory}.")
> FileNotFoundError: Couldn't find any class folder in D:\LEO\2-Estudos\sem8\tcc2\git reconhecimento de expressoes\EfficientFace\train.
> ```
> 
> Can you help me?



> I'm trying to run the project on my pc, but i keep running into the following error:
> 
> ```
> Traceback (most recent call last):
>   File "D:\LEO\2-Estudos\sem8\tcc2\git reconhecimento de expressoes\EfficientFace\main.py", line 383, in <module>
>     main()
>   File "D:\LEO\2-Estudos\sem8\tcc2\git reconhecimento de expressoes\EfficientFace\main.py", line 99, in main
>     train_dataset = datasets.ImageFolder(traindir,
>   File "C:\Users\leodo\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\datasets\folder.py", line 310, in __init__
>     super(ImageFolder, self).__init__(root, loader, IMG_EXTENSIONS if is_valid_file is None else None,
>   File "C:\Users\leodo\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\datasets\folder.py", line 145, in __init__
>     classes, class_to_idx = self.find_classes(self.root)
>   File "C:\Users\leodo\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\datasets\folder.py", line 221, in find_classes
>     return find_classes(directory)
>   File "C:\Users\leodo\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\datasets\folder.py", line 42, in find_classes
>     raise FileNotFoundError(f"Couldn't find any class folder in {directory}.")
> FileNotFoundError: Couldn't find any class folder in D:\LEO\2-Estudos\sem8\tcc2\git reconhecimento de expressoes\EfficientFace\train.
> ```
> 
> Can you help me?

Sorry, I did not run the code on the PC environment.

**Comment by zengqunzhao** [comment]
> 

Using "checkpoint = torch.load('./checkpoint/mdoel_name.tar')"

Best

**Comment by zengqunzhao** [comment]
> The compressed package of pth cannot be decompressed as a tar file. What statements do you need to decompress open tar

Using "checkpoint = torch.load('./checkpoint/model_name.tar')"
