### ISSUE TITLE
预训练

### ISSUE THREAD

**Issue by zhang6666** [zengqunzhao/EfficientFace#16]
你好，请问可以提供用来训练PresientFace和LDG以获得预先训练的模型的代码吗？

**Comment by zengqunzhao** [comment]
> PresientFace

LDG就是用的50层的ResNet，用我release的预训练模型，在相应的FER-dataset上微调下就可以了。“训练PresientFace”这个没看懂。

**Comment by zengqunzhao** [comment]
> 你好，请问可以提供用来训练PresientFace和LDG以获得预先训练的模型的代码吗？

LDG就是用的50层的ResNet，用我release的预训练模型，在相应的FER-dataset上微调下就可以了。“训练PresientFace”这个没看懂。

**Comment by zhang6666** [comment]
您好，请问是您上传的哪个预训练模型？

**Comment by zengqunzhao** [comment]
> 您好，请问是您上传的哪个预训练模型？

在README里面的Pre-trained Models看下。
