### ISSUE TITLE
训练数据集

### ISSUE THREAD

**Issue by suiyiyid** [zengqunzhao/EfficientFace#17]
你好，按照步骤训练新的数据集准确率很低，是有忽略的地方吗？

**Comment by zengqunzhao** [comment]
> 你好，按照步骤训练新的数据集准确率很低，是有忽略的地方吗？

额，你问的有点宽泛了，真不知道咋回答。要注意的是，LDG网络需要在相应的FER数据集上微调下，不然的话，生成的表情分布不准确。或者你可以详述你遇到问题。

**Comment by suiyiyid** [comment]
你好，请问如何微调LDG网络？可以具体说明下吗？

**Comment by zengqunzhao** [comment]
> 你好，请问如何微调LDG网络？可以具体说明下吗？

论文中LDG用的就是ResNet50，你直接用我release的pre-train model (on MS-Celeb-1M)导入预训练模型。然后在相应的FER数据集上微调下，比较小的learning rate就可以。
