### ISSUE TITLE
Change the order of expressions

### ISSUE THREAD

**Issue by DJdjUSER** [zengqunzhao/EfficientFace#18]
If I want to change the order of the categories, for example, 0 is no longer the neutral, but the expression representing sadness, what should I change in the code

**Comment by zengqunzhao** [comment]
> If I want to change the order of the categories, for example, 0 is no longer the neutral, but the expression representing sadness, what should I change in the code

Hi, you needn't do anything for the code part if the pre-train model does not use. Or you need to keep it the same.
