### ISSUE TITLE
关于测试问题

### ISSUE THREAD

**Issue by T-dollar** [zengqunzhao/EfficientFace#19]
作者你好，我使用你的代码然后能跑到你论文里面的精度，但是我使用-e参数，加载我训练的最好精度的pth文件之后，得到的结果却很低。我想知道，怎么使用-e 参数去验证模型的精度。
<img width="489" alt="image" src="https://user-images.githubusercontent.com/72782835/202887102-95208a51-be93-4139-b2f3-450a81bd03ee.png">

**Comment by hzx1105** [comment]
> 作者你好，我使用你的代码然后能跑到你论文里面的精度，但是我使用-e参数，加载我训练的最好精度的pth文件之后，得到的结果却很低。我想知道，怎么使用-e 参数去验证模型的精度。 <img alt="image" width="489" src="https://user-images.githubusercontent.com/72782835/202887102-95208a51-be93-4139-b2f3-450a81bd03ee.png">

你好，我想找您咨询一下，The trained EfficientFace model on RAF-DB, CAER-S, AffectNet-7, and AffectNet-8 这些模型你都下载了吗?我的Google driver一直打不开，如果你之前已经下载能否给我发一份啊，不胜感激！

**Comment by hzx1105** [comment]
作者你好，我想找您咨询一下，The trained EfficientFace model on RAF-DB, CAER-S, AffectNet-7, and AffectNet-8 这些模型你都下载了吗?我的Google driver一直打不开，如果你之前已经下载能否给我发一份啊，不胜感激！

**Comment by zengqunzhao** [comment]
> 作者你好，我想找您咨询一下，The trained EfficientFace model on RAF-DB, CAER-S, AffectNet-7, and AffectNet-8 这些模型你都下载了吗?我的Google driver一直打不开，如果你之前已经下载能否给我发一份啊，不胜感激！

Hi, 我这边打开下载正常，请检查你那边的网络。

**Comment by sumeetssaurav** [comment]
Hii @T-dollar Did your issue got resolved? I am also facing the similar issue, can you help me with it.
