### ISSUE TITLE
关于实验结果

### ISSUE THREAD

**Issue by wanghyxq** [zengqunzhao/EfficientFace#20]
你好，我最近在跑您这篇论文的代码，可是我在RAF-DB上的精度一直都在79%徘徊，没法跑到论文中说的效果，请问您能给我一些建议吗。

**Comment by zengqunzhao** [comment]
> 

Hi,

不知道你哪里设置是不是有问题，根据其他人遇到的问题，你可能需要check下：1，两个model的预训练模型是否导入正确；2，LDG模块都是在相应的表情数据集上fine-tune过的，导入的时候注意匹配，3，超参是否设置在合理的范围，具体参照code里给的，不过也要根据具体情况微调下。

**Comment by wanghyxq** [comment]
好的，谢谢您




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zengqun ***@***.***&gt;; 
发送时间: 2023年4月14日(星期五) 下午4:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zengqunzhao/EfficientFace] 关于实验结果 (Issue #20)





   
Hi,
 
不知道你哪里设置是不是有问题，根据其他人遇到的问题，你可能需要check下：1，两个model的预训练模型是否导入正确；2，LDG模块都是在相应的表情数据集上fine-tune过的，导入的时候注意匹配，3，超参是否设置在合理的范围，具体参照code里给的，不过也要根据具体情况微调下。

**Comment by ranran08181130** [comment]
您好，请问可以分享一下RAF-DF数据集的资源吗？我最近急需RAF-DB数据集，如果方便的话您可以分享一下吗？
