### ISSUE TITLE
recorder meter error 

### ISSUE THREAD

**Issue by andrearafanelli** [zengqunzhao/EfficientFace#26]
Hi, thank you for sharing your pre-trained weights on ms-celeb-1m, but error occurs when I load resnet18 weights using torch.load: AttributeError: Can't get attribute 'RecorderMeter' on <module 'main', do you have any idea about this error?

**Comment by hankyuwon** [comment]
Have you solved the problem?

**Comment by zengqunzhao** [comment]
Hi all, just put the following code in:

class RecorderMeter(object):
    pass
