### ISSUE TITLE
预训练模型压缩包无法打开

### ISSUE THREAD

**Issue by TheKOne** [zengqunzhao/EfficientFace#3]
您好！我从您给的谷歌云盘链接去下载预训练模型后，无法解压缩，显示无法打开

**Comment by zengqunzhao** [comment]
感谢关注，
我刚下载解压是没问题的，请检查您那边的网络，以及文件是否完整下载。

**Comment by TheKOne** [comment]
> 
> 
> 感谢关注，
> 我刚下载解压是没问题的，请检查您那边的网络，以及文件是否完整下载。

您好，我是完整下载了好几遍，首先下载下来是models.rar，然后解压后得到两个预训练模型压缩包：Pretrained_EfficientFace.tar和Pretrained_LDG.tar，我自己电脑是windows环境，然后我尝试了各种解压缩办法，都显示文件类型未知或已损坏。

**Comment by zengqunzhao** [comment]
两个tar文件就是预训练模型，请仔细看下main.py

**Comment by TheKOne** [comment]
> 
> 
> 两个tar文件就是预训练模型，请仔细看下main.py

好的，明白了，我是刚看完您的论文，然后就去github上下载了，以为里面的两个.tar还得解压！实在是抱歉，我自己还没仔细看过您提供的源代码就仓促来问您了。感谢您的及时回复，论文写的很好，有很多值得思考和借鉴的地方，希望后面详细看完代码之后还能来请教您，再次感谢！

**Comment by zengqunzhao** [comment]
> > 感谢关注，
> > 我刚下载解压是没问题的，请检查您那边的网络，以及文件是否完整下载。
> 
> 您好，我是完整下载了好几遍，首先下载下来是models.rar，然后解压后得到两个预训练模型压缩包：Pretrained_EfficientFace.tar和Pretrained_LDG.tar，我自己电脑是windows环境，然后我尝试了各种解压缩办法，都显示文件类型未知或已损坏。

两个tar文件就是预训练模型，请仔细看下main.py
