### ISSUE TITLE
Ask about Retinaface in image preprocessing 

### ISSUE THREAD

**Issue by Dearbreeze** [zengqunzhao/EfficientFace#6]
Hi Zengqun
Thanks for you share this nice work!
I want to know which part of the code reflects that you said in your paper that '' the face region is detected and aligned using Retinaface". I carefully looked at the preprocessing part of the code and it seemed that I could not find it.
Sure, I'm just beginning to study facial expression recognition so please forgive me if the problem is too simple.
I am very grateful for any replies from you

**Comment by zengqunzhao** [comment]
> Hi Zengqun
> Thanks for you share this nice work!
> I want to know which part of the code reflects that you said in your paper that '' the face region is detected and aligned using Retinaface". I carefully looked at the preprocessing part of the code and it seemed that I could not find it.
> Sure, I'm just beginning to study facial expression recognition so please forgive me if the problem is too simple.
> I am very grateful for any replies from you

Thanks for your attention.
The pre-processing is an off-line part. We first crop the face region and then training the model. The RetinaFace code can be found here (https://github.com/deepinsight/insightface/tree/master/detection/retinaface).

**Comment by Dearbreeze** [comment]
> > Hi Zengqun
> > Thanks for you share this nice work!
> > I want to know which part of the code reflects that you said in your paper that '' the face region is detected and aligned using Retinaface". I carefully looked at the preprocessing part of the code and it seemed that I could not find it.
> > Sure, I'm just beginning to study facial expression recognition so please forgive me if the problem is too simple.
> > I am very grateful for any replies from you
> 
> Thanks for your attention.
> The pre-processing is an off-line part. We first crop the face region and then training the model. The RetinaFace code can be found here (https://github.com/deepinsight/insightface/tree/master/detection/retinaface
