### ISSUE TITLE
Question about combining channel and spatial heatmaps

### ISSUE THREAD

**Issue by alvin870203** [zengqunzhao/EfficientFace#7]
Hi, Zeng Qun,

Thank you for sharing this great work.
I noticed that in your paper and also in the BAM,
the channel heatmaps M<sub>c</sub>(F<sub>stage2</sub>) and the spatial heatmaps M<sub>s</sub>(F<sub>stage2</sub>) were "added" before being passed through sigmoid.
But in your code, they were "multiplied" before being passed through sigmoid.
https://github.com/zengqunzhao/EfficientFace/blob/328cb992915ed8c2dcbae351a8d9da718c117d8f/models/modulator.py#L58
I wonder if there is any interesting reason for you to do it differently ? 
Thanks.

**Comment by zengqunzhao** [comment]
> Hi, Zeng Qun,
> 
> Thank you for sharing this great work.
> I noticed that in your paper and also in the BAM,
> the channel heatmaps Mc(Fstage2) and the spatial heatmaps Ms(Fstage2) were "added" before being passed through sigmoid.
> But in your code, they were "multiplied" before being passed through sigmoid.
> https://github.com/zengqunzhao/EfficientFace/blob/328cb992915ed8c2dcbae351a8d9da718c117d8f/models/modulator.py#L58
> 
> 
> I wonder if there is any interesting reason for you to do it differently ?
> Thanks.

Thanks for your attention.
I think that combining Mc and Ms by multiplying can enlarge the weight between important and unimportant elements. The  "addition" in the paper is just a general statement. 

Best,
Zengqun

**Comment by alvin870203** [comment]
Thanks for your explanation
